version: '3.9'

services:
  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serverdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  cruiseapp:
    environment: 
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cruisedb
      - DB_SSL_MODE=disable
    build:
      context: .
      image: cruiseapp
      dockerfile: Dockerfile
    ports:
      - 8080:8080


volumes:
  pgdata:
